### ISSUE TITLE
pip installation misses ra.top_search module

### ISSUE THREAD

**Issue by dhinojosaec** [ra-systems/django-ra-erp#10]
The pip installation command is missing the ra.top_search module.

Starting a new application gets the following error:
ModuleNotFoundError: No module named 'ra.top_search'

After copying the ra/top_search folder from the source code, the project runs well.

**Comment by RamezIssac** [comment]
Hello, sorry for the delayed reply.
There is an new release that really should be published in a day or two. and this issue will be fixed along .

Thanks !

**Comment by mohammed-Emad** [comment]
and +1
Thanks !

**Comment by podolyanyn** [comment]
@dhinojosaec, thanks !

**Comment by RamezIssac** [comment]
Hello mates. 
A new version has been  released. It should have this issue, and many other, fixed.

Feel free to try it out on your time.

Thanks and have a lovely day

**Comment by RamezIssac** [comment]
Closing after the new release https://pypi.org/project/django-ra-erp/1.1.0/
