### ISSUE TITLE
has no ForeignKey to 'document_control.SalesTransaction'

### ISSUE THREAD

**Issue by youssriaboelseod** [ra-systems/django-ra-erp#12]
hi Ramiz
i hope you is fine

i follows your instrument here
https://ra-framework.readthedocs.io/en/latest/tutorial/tutorial_1.html

but i get this error 
![Capture](https://user-images.githubusercontent.com/40850682/91310667-74eb6400-e7b2-11ea-8543-29f3df534d3b.PNG)

**Comment by RamezIssac** [comment]
Thanks for pointing this out.
class `SalesLineTransaction` is missing this line 
`sales_transaction = models.ForeignKey(SalesTransaction, on_delete=models.CASCADE)`
Updating the docs..

**Comment by youssriaboelseod** [comment]
thanks
