### ISSUE TITLE
Invalid filter: 'jazzy_admin_url'

### ISSUE THREAD

**Issue by luki922** [ra-systems/django-ra-erp#16]
After login to admin panel we will get error:
```
TemplateSyntaxError
Invalid filter: 'jazzy_admin_url'
```
File:
`lib/python3.8/site-packages/ra/admin/templates/ra/sidebar.html, error at line 24`

Need to change:
from: `<a href="{{ request.user|jazzy_admin_url }}" class="d-block">{{ request.user }}</a>`
to: `<a href="{% jazzy_admin_url request.user %}" class="d-block">{{ request.user }}</a>`

**Comment by pierreclaverkoko** [comment]
Without changing the template, you can change jazzmin position in INSTALLED_APPS in settings.py

Just move it before all ra apps. This fixes the issue without changing ra template.

**Comment by RamezIssac** [comment]
Thank you @luki922 @pierreclaverkoko !
This should be fixed in the new release https://pypi.org/project/django-ra-erp/1.1.0/
