### ISSUE TITLE
diverse between install backage and gitup

### ISSUE THREAD

**Issue by youssriaboelseod** [ra-systems/django-ra-erp#18]
hi Ramiz
thank your for your best ERB

i work hard to pull requests for more functionality but i noteced that
defference between the copy was installed and this in django-ra-erp\ra\base.models

for example in installed package you can find following but you can't find it in the same location in Githup

```
class BasePersonInfo(BaseInfo):
    address = models.CharField(_('address'), max_length=260, null=True, blank=True)
    telephone = models.CharField(_('telephone'), max_length=130, null=True, blank=True)
    email = models.EmailField(_('email'), null=True, blank=True)

    class Meta:
        abstract = True
        # swappable = swapper.swappable_setting('ra', 'BasePersonInfo')

```

i will send pull request for fix this

**Comment by RamezIssac** [comment]
Hello @youssriaboelseod 
With the release https://pypi.org/project/django-ra-erp/1.1.0/ the github and pypi code are now synced.
Let me know if you find any other issues. Thanks !
