### ISSUE TITLE
AttributeError: 'ManyToOneRel' object has no attribute 'verbose_name'

### ISSUE THREAD

**Issue by mswastik** [ra-systems/django-ra-erp#20]
Getting `AttributeError: 'ManyToOneRel' object has no attribute 'verbose_name'` whenever I include a group_by option under class in `@register_report_view`

![Screenshot_20201004_094141](https://user-images.githubusercontent.com/7689061/95006827-1d001280-0626-11eb-8836-cf441e0e2253.png)

**Comment by RamezIssac** [comment]
This is "Django Slick Reporting" related.
I believe already fixed.
