### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: jazzmin

### ISSUE THREAD

**Issue by AhmedSalam22** [ra-systems/django-ra-erp#21]
Hi, What should I do?

![Screenshot (343)](https://user-images.githubusercontent.com/35177448/96046824-66493100-0e74-11eb-9d69-c7a3762acdbf.png)

Thank's

**Comment by joff13** [comment]
hi edit the settings.py file and remove one of the two  lines  'jazzmin', from INSTALLED_APPS
(same issue for me right now)

**Comment by AhmedSalam22** [comment]
@joff13  Thank you so much. Have a nice time but another error appear to you have a solution ?
![image](https://user-images.githubusercontent.com/35177448/96169806-ff368580-0f22-11eb-89ed-2d8258f4b783.png)

**Comment by megamayoy** [comment]
@AhmedSalam22 
the django.utils.six module was removed starting from Django 3.0 so , all you need to do is upgrade the django-compressor from 2.3 to 2.4 by running 
`pip install django-compressor==2.4`
that worked for me

**Comment by RamezIssac** [comment]
Already Solved. Feel free to reopen if not.
Thanks

**Comment by AkshataABhat** [comment]
Can you please help me with this?
![image](https://user-images.githubusercontent.com/74967139/166944540-eb8070e4-8fa0-4629-8358-399769e218d2.png)

**Comment by tobiolusa** [comment]
Well, what i had to do to solve the error was to change the name of my app from auth to authapp and it works fine.
