### ISSUE TITLE
cannot import name 'six' from 'django.utils' (I:\erp\erp\lib\site-packages\django\utils\__init__.py)

### ISSUE THREAD

**Issue by AhmedSalam22** [ra-systems/django-ra-erp#22]
Hi, I face this issue. What should I do?
![Screenshot (345)](https://user-images.githubusercontent.com/35177448/96170032-54729700-0f23-11eb-8e18-891e68d8f488.png)

Thank's

**Comment by megamayoy** [comment]
@AhmedSalam22
the django.utils.six module was removed starting from Django 3.0 so , all you need to do is upgrade the django-compressor version from 2.3 to 2.4 by running
`pip install django-compressor==2.4`

Hope this helps

**Comment by AhmedSalam22** [comment]
@megamayoy  thank you so much

**Comment by loleg** [comment]
Alternatively, remove **compressor** from your `settings.py` if you don't plan to use for the time being, and the project starts up just fine.
