### ISSUE TITLE
there are still deviation between github backage and pypipacake

### ISSUE THREAD

**Issue by youssriaboelseod** [ra-systems/django-ra-erp#24]
dear Ramz
there are still major deviation between pypi package and github backage

i can't create developing in your project for that

are i send pull request for adjust your now repository as pypi backage? or what?

**Comment by youssriaboelseod** [comment]
for example where are  RaAdmin, RaMovementAdmin in last githup backage? or where its alternative?

its still found in pybi package

**Comment by RamezIssac** [comment]
latest release have https://pypi.org/project/django-ra-erp/1.3.1/
